### ISSUE TITLE
Error in topology: usage of typing.NamedTuple in spl.Source expects list of schema

### ISSUE THREAD

**Issue by rnostream** [IBMStreams/pypi.streamsx.mqtt#2]
Opened IBMStreams/streamsx.topology#2313

When issue is solved the test has to be adapted. Actually mqtt_source() wrapper needs to be called with a list of a single typing.NamedTuple schema.

**Comment by ghost** [comment]
IBMStreams/streamsx.topology#2313 has been resolved.
Test case has been removed. Tested function has been replaced by composite.
